FROM python:3.10-slim

WORKDIR /app
COPY ./api-python /app

RUN pip install --default-timeout=1000 --no-cache-dir -r requirements.txt

EXPOSE 8001
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
